version: "1.40.{build}"

#vc140
os: Visual Studio 2015

configuration:
  - Debug
  - Release

init:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: msbuild /version

clone_folder: C:\projects\VisualStudioCppExtensions

build:
  project: $(APPVEYOR_BUILD_FOLDER)\VisualStudioCppExtensions.sln
  parallel: true
  verbosity: normal

before_build:
  - nuget restore $(APPVEYOR_BUILD_FOLDER)\VisualStudioCppExtensions.sln -Verbosity quiet

test: off
